### ISSUE TITLE
WebExtensions version cannot find logins after installing in place of old version

### ISSUE THREAD

**Issue by DoumanAsh** [sarahavilov/secure-login#15]
Ok, so in my setup i use `PassIFox` as password storage.
Secure Login works with it out of box, but when i installed WebExtensions version button click produces pop-up message that no credentials can be found.

I'm not sure how to help you out to debug it, but feel free to point way out.

**Comment by sarahavilov** [comment]
For KeePass integration, I would recommend https://addons.mozilla.org/en-Us/firefox/addon/keepasshelper/ 
It does not send and receive anything unless otherwise you actually open the panel.

Note that `PassIFox` is not yet WebExtension and hence there is no way to communicate with this extension.

BTW, what feature is missing in `PassIFox` that you need the integration for?

**Comment by DoumanAsh** [comment]
Oh, i didn't know details of how `PasssIFox` is implemented and how it affects Secure Login.
There are no features i suppose i'm bound to.

I'll try `KeePassHelper`, sorry for false alarm

**Comment by DoumanAsh** [comment]
Btw, are there plans to support keepass storage for Secure login? At least currently it seems to use Firefox's builtin password manager only

**Comment by sarahavilov** [comment]
We actually can support, but I am going to wait to see what is going to happen to the built-in password manager. At this point, still we need low level APIs to access it. When high level APIs are ready, I'll see if I can borrow some code from https://addons.mozilla.org/en-Us/firefox/addon/keepasshelper/ to add KeePass integration.
