### ISSUE TITLE
Javascript validation

### ISSUE THREAD

**Issue by 4wakened5leeper** [sarahavilov/secure-login#3]
Some craypy forms (like the Sogo login page of my corporate webmail) uses a javascript function instead of form validation to validate the form.
Would it be possible to add a feature to handle that kind of form ? (With Angular and other frameworks, I think that it will happen more and more often)

**Comment by sarahavilov** [comment]
How about https://addons.mozilla.org/en-US/firefox/addon/log-me-in/?

**Comment by matthiasries** [comment]
same problem with Shopware. The backend uses ExtJs and not a real form element.

**Comment by sarahavilov** [comment]
@matthiasries SL can login to Shopware. Please provide a sample page with login issue

@Necriis can you provide a sample page with this issue?

**Comment by brother** [comment]
I think I have been bitten by this or at least something close to it.

When I visit https://cloud.glesys.com it clearly detects the login form and by pushing my keyboard shortcut for fast login the credentials are showing in the form but the form is not posted. Furthermore the login button is not activated, probably because ember can not detect that the form is properly filled). I need to click/navigate to the username and password fields before I can post the login.

Video: https://youtu.be/nto520nsUzc

**Comment by sarahavilov** [comment]
@brother version 0.1.8 most likely fixes this issue. Please let me know if not.

**Comment by brother** [comment]
@sarahavilov I have now restarted my browser and tried the web extension version and can confirm that it does indeed work. Thanks!
